### ISSUE TITLE
Api still working ?

### ISSUE THREAD

**Issue by raveen2003** [nstrydom2/anonfile-api#51]
stat: path should be string, bytes, os.PathLike or integer, not NoneType
'NoneType' object has no attribute 'url'
Traceback (most recent call last):
  File "/home/raveen/.local/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/raveen/Desktop/projects/MUltiFilesB/bot.py", line 59, in anon_up
    print(upload.url.geturl())
AttributeError: 'NoneType' object has no attribute 'url'

[my usage](https://paste.theostrich.eu.org/yalexosupa)

**Comment by hentai-chan** [comment]
In theory yes, but there's a problem with the test suite though that I haven't been able to solve yet (unit tests pass locally but not in GitHub Actions). The current version only supports up- and download of (small) text files, the patch increases this limit to ~450MB per call; partly because `requests_toolbelt` is implemented in Python and not C. @nstrydom2 could you test this PR locally and, if `pytest` doesn't err out, initiate the merge to create a pre-release until we figure out a solution for the test scripts? Let me know if you want to proceed with this idea and I'll update the version string and add a remark in the README.
